### ISSUE TITLE
どのクローラに仕事をさせるかを指定するための before メソッドがほしい

### ISSUE THREAD

**Issue by yucao24hours** [bm-sms/daimon_skycrawlers#103]
`DaimonSkycrawlers::Processor::Base` にある `before_process` があるように、クローラ側にも `DaimonSkycrawlers::Crawler::Base` に `before_crawl` のようなメソッドがほしいと思ったのですが追加しないでしょうか？（なにか方針があるのかもと思ったので確認です）

プロセッサ内で `DaimonSkycrawlers::Crawler.enqueue_url "http://hoge.com` したあとに再度クローラ側でメッセージを受け取ったとき、どのクローラが動いてほしいかを（Filter を使って）指定したいなと思いました。その際に `before_crawl` のようなメソッドがあれば、そこで実行できるかなと思いました。

**Comment by yucao24hours** [comment]
次はどのクローラに仕事をさせるか文字列で指定できるようにする、というお話は伺っているので、それに任せるとして `before_*` 系は使わない（実装しない）という感じなんですかね... ❓

**Comment by okkez** [comment]
> 次はどのクローラに仕事をさせるか文字列で指定できるようにする
それは、もっと汎用的な仕組みを実装したつもりだったんですが、現状だと crawler からは使えないですね。。。

なんか実装します。

**Comment by okkez** [comment]
#104 で実装してみました。
