### ISSUE TITLE
Support params

### ISSUE THREAD

**Issue by myokoym** [bm-sms/daimon_skycrawlers#48]
`params` should be a part of `path`. such as `path == "/hoi?hi=yoyo"`
- https://github.com/bm-sms/daimon-skycrawlers/pull/47/files#diff-97a5056b1736a652d624b847ceca6df9R55
- https://github.com/bm-sms/daimon-skycrawlers/pull/47/files#diff-97a5056b1736a652d624b847ceca6df9R59

**Comment by okkez** [comment]
Not needed.
Because we can specify parameters in a URL.
