### ISSUE TITLE
どのファイルをどう使うかわかりやすくなっているとうれしい

### ISSUE THREAD

**Issue by yucao24hours** [bm-sms/daimon_skycrawlers#61]
どのファイルをユーザがカスタマイズできるか（するべきか）がわかるように、ファイルの中にコメントなどで簡単な説明などが書いてあるとうれしいなと思いました。もしくはフレームワーク側で読み込むファイル名を固定してしまうとか。
（今の状態だと、新しくファイルをつくるべきなのか、所定のファイルを編集すればいいのかパット見ではわかりにくい気がしたので）

クローラー定義用のファイル名がデフォルトで `crawler.rb` になっているだけで、定義と起動スクリプトさえ書いてあればどの（どんな名前の）ファイルでも大丈夫なようになってると思うんですが、ある程度取り決めがあったほうが使う側は考えることが減るのかなとか思っていました。（と書いていて、自分が rails ばかり使いすぎで rails 脳になっているのかもしれないとも思いました 😥 ）

**Comment by okkez** [comment]
Done.

app/crawler.rb, app/processor.rb を見れば全体の流れがわかるようになった。
